Created tests for book and service repositories, services, and controllers
RostyslavKuzmych/book_store pull request #15
Opened 2023-12-15 16:28 UTC by RostyslavKuzmych

2023-12-18 07:01 UTC, kshuryhin requested changes
great job, but there are some points to consider

2023-12-19 10:18 UTC, bhdnchui requested changes
Just a few points to consider.

2023-12-19 10:18 UTC, bhdnchui commented on src/main/java/application/controller/BookController.java
> +    public static final String SEARCH_URL = "/search";
It is weird to add constants if the task is to add tests.
I saw Kostia`s comment, but pay attention that it is regarding tests.

2023-12-20 13:48 UTC, vovasalyha approved these changes

2023-12-21 13:13 UTC, merged